language: "jp"
early_access: true
reviews:
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - ["public/**","private/**"]
  path_instructions:
    - path: "**"
      instructions: "この記事はQiitaに投稿する技術記事です。多くの人が記事を読んでくれるように、題名のつけ方、わかりやすい書き方、コード上の誤りなどについて指摘してください。"
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "**"
chat:
  auto_reply: true